name: SimpleGuilds
version: '1.0'
main: me.lightning.simpleguilds.SimpleGuilds
api-version: '1.21'

commands:
  guild:
    description: Manage your guild.
  guildchat:
    description: Message all members of your guild.
    aliases: [gc, gchat]
